Clarify error when a template is missing
Currently when passing a non-existing template the following error is
output:

  $ openstack overcloud deploy --templates -e /tmp/nonexistant.yaml
  Deploying templates in the directory /usr/share/openstack-tripleo-heat-templates
  The files ('overcloud-without-mergepy.yaml', 'overcloud.yaml') not found
  in the /usr/share/openstack-tripleo-heat-templates/ directory

Add a proper error instead:

  $ openstack overcloud deploy --templates -e /tmp/nonexistant.yaml -e /tmp/foo2.yaml
  Deploying templates in the directory /usr/share/openstack-tripleo-heat-templates
  Error: The following files were not found: /tmp/nonexistant.yaml, /tmp/foo2.yaml

Change-Id: I05bcd5e42d553cdac507d5e31a63cbcef4ab975c
Closes-Bug: #1548385