Revert "Scale out overcloud"
This reverts commit 435aedd4170ae4e91c0f3153f51adfaae5ee0100.

Due to error ($ openstack --help): Could not load EntryPoint.parse('baremetal_configure_boot = rdomanager_oscplugin.v1.baremetal:ConfigureBootPlugin')
ERROR: openstack 'ArgumentParser' object has no attribute 'debug'

Change-Id: I350f7ba3ed0737d6b407e82d5d89be444699119f