Fix overcloud cell export after refactoring
https://review.opendev.org/692909 introduced overcloud export and
refactored the overcloud cell export command which introduces an
issue when calling the cell export:

  File "/usr/lib/python2.7/site-packages/tripleoclient/v1/overcloud_cell.py",
line 94, in take_action
    data['parameter_defaults'].update(export.export_stack(
KeyError: 'parameter_defaults'
'parameter_defaults'

Change-Id: Ic6b76e31885d0e0b59a650dbd4148b245f6057d6
Closes-Bug: #1852402
Related-Bug: #1850636